dmoj/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from django.http import Http404, HttpResponsePermanentRedirect
from django.templatetags.static import static
from django.urls import include, path, re_path, reverse
from django.utils.functional import lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import RedirectView
from martor.views import markdown_search_user

from judge.feed import AtomBlogFeed, AtomCommentFeed, AtomProblemFeed, BlogFeed, CommentFeed, ProblemFeed
from judge.sitemap import sitemaps
from judge.views import TitledTemplateView, api, blog, comment, contests, language, license, mailgun, organization, \
    preview, problem, problem_manage, ranked_submission, register, stats, status, submission, tasks, ticket, \
    two_factor, user, widgets
from judge.views.problem_data import ProblemDataView, ProblemSubmissionDiff, \
    problem_data_file, problem_init_view
from judge.views.register import ActivationView, RegistrationView
from judge.views.select2 import AssigneeSelect2View, ClassSelect2View, CommentSelect2View, ContestSelect2View, \
    ContestUserSearchSelect2View, OrganizationSelect2View, ProblemSelect2View, TicketUserSelect2View, \
    UserSearchSelect2View, UserSelect2View
from judge.views.widgets import martor_image_uploader

admin.autodiscover()

register_patterns = [
    path('activate/complete/',
         TitledTemplateView.as_view(template_name='registration/activation_complete.html',
                                    title=_('Activation Successful!')),
         name='registration_activation_complete'),
    # Let's use <str:activation_key>, because a bad activation key should still get to the view;
    # that way, it can return a sensible "invalid key" message instead of a confusing 404.
    path('activate/<str:activation_key>/', ActivationView.as_view(), name='registration_activate'),
    path('register/', RegistrationView.as_view(), name='registration_register'),
    path('register/complete/',
         TitledTemplateView.as_view(template_name='registration/registration_complete.html',
                                    title=_('Registration Completed')),
         name='registration_complete'),
    path('register/closed/',
         TitledTemplateView.as_view(template_name='registration/registration_closed.html',
                                    title=_('Registration Not Allowed')),
         name='registration_disallowed'),
    path('login/', user.CustomLoginView.as_view(), name='auth_login'),
    path('logout/', user.UserLogoutView.as_view(), name='auth_logout'),
    path('password/change/', user.CustomPasswordChangeView.as_view(), name='password_change'),
    path('password/change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='registration/password_change_done.html',
    ), name='password_change_done'),
    path('password/reset/', user.CustomPasswordResetView.as_view(), name='password_reset'),
    re_path(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
            auth_views.PasswordResetConfirmView.as_view(
                template_name='registration/password_reset_confirm.html',
            ), name='password_reset_confirm'),
    path('password/reset/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html',
    ), name='password_reset_complete'),
    path('password/reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password_reset_done.html',
    ), name='password_reset_done'),
    path('social/error/', register.social_auth_error, name='social_auth_error'),

    path('2fa/', two_factor.TwoFactorLoginView.as_view(), name='login_2fa'),
    path('2fa/enable/', two_factor.TOTPEnableView.as_view(), name='enable_2fa'),
    path('2fa/refresh/', two_factor.TOTPRefreshView.as_view(), name='refresh_2fa'),
    path('2fa/disable/', two_factor.TOTPDisableView.as_view(), name='disable_2fa'),
    path('2fa/webauthn/attest/', two_factor.WebAuthnAttestationView.as_view(), name='webauthn_attest'),
    path('2fa/webauthn/assert/', two_factor.WebAuthnAttestView.as_view(), name='webauthn_assert'),
    path('2fa/webauthn/delete/<int:pk>', two_factor.WebAuthnDeleteView.as_view(), name='webauthn_delete'),
    path('2fa/scratchcode/generate/', user.generate_scratch_codes, name='generate_scratch_codes'),

    path('api/token/generate/', user.generate_api_token, name='generate_api_token'),
    path('api/token/remove/', user.remove_api_token, name='remove_api_token'),
]


def exception(request):
    if not request.user.is_superuser:
        raise Http404()
    raise RuntimeError('@Xyene asked me to cause this')


def paged_list_view(view, name):
    return include([
        path('', view.as_view(), name=name),
        path('<int:page>', view.as_view(), name=name),
    ])


urlpatterns = [
    path('', blog.PostList.as_view(template_name='home.html', title=_('Home')), kwargs={'page': 1}, name='home'),
    path('500/', exception),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('accounts/', include(register_patterns)),
    path('', include('social_django.urls')),

    path('problems/', problem.ProblemList.as_view(), name='problem_list'),
    path('problems/random/', problem.RandomProblem.as_view(), name='problem_random'),

    path('problem/<str:problem>', include([
        path('', problem.ProblemDetail.as_view(), name='problem_detail'),
        path('/editorial', problem.ProblemSolution.as_view(), name='problem_editorial'),
        path('/pdf', problem.ProblemPdfView.as_view(), name='problem_pdf'),
        path('/pdf/<slug:language>', problem.ProblemPdfView.as_view(), name='problem_pdf'),
        path('/clone', problem.ProblemClone.as_view(), name='problem_clone'),
        path('/submit', problem.ProblemSubmit.as_view(), name='problem_submit'),
        path('/resubmit/<int:submission>', problem.ProblemSubmit.as_view(), name='problem_submit'),

        path('/rank/', paged_list_view(ranked_submission.RankedSubmissions, 'ranked_submissions')),
        path('/submissions/', paged_list_view(submission.ProblemSubmissions, 'chronological_submissions')),
        path('/submissions/<str:user>/', paged_list_view(submission.UserProblemSubmissions, 'user_submissions')),

        path('/', lambda _, problem: HttpResponsePermanentRedirect(reverse('problem_detail', args=[problem]))),

        path('/test_data', ProblemDataView.as_view(), name='problem_data'),
        path('/test_data/init', problem_init_view, name='problem_data_init'),
        path('/test_data/diff', ProblemSubmissionDiff.as_view(), name='problem_submission_diff'),
        path('/data/<path:path>', problem_data_file, name='problem_data_file'),

        path('/tickets', ticket.ProblemTicketListView.as_view(), name='problem_ticket_list'),
        path('/tickets/new', ticket.NewProblemTicketView.as_view(), name='new_problem_ticket'),

        path('/vote', problem.ProblemVote.as_view(), name='problem_vote'),
        path('/vote/delete', problem.DeleteProblemVote.as_view(), name='delete_problem_vote'),
        path('/vote/stats', problem.ProblemVoteStats.as_view(), name='problem_vote_stats'),

        path('/manage/submission', include([
            path('', problem_manage.ManageProblemSubmissionView.as_view(), name='problem_manage_submissions'),
            path('/rejudge', problem_manage.RejudgeSubmissionsView.as_view(), name='problem_submissions_rejudge'),
            path('/rejudge/preview', problem_manage.PreviewRejudgeSubmissionsView.as_view(),
                 name='problem_submissions_rejudge_preview'),
            path('/rejudge/success/<slug:task_id>', problem_manage.rejudge_success,
                 name='problem_submissions_rejudge_success'),
            path('/rescore/all', problem_manage.RescoreAllSubmissionsView.as_view(),
                 name='problem_submissions_rescore_all'),
            path('/rescore/success/<slug:task_id>', problem_manage.rescore_success,
                 name='problem_submissions_rescore_success'),
        ])),
    ])),

    path('submissions/', paged_list_view(submission.AllSubmissions, 'all_submissions')),
    path('submissions/user/<str:user>/', paged_list_view(submission.AllUserSubmissions, 'all_user_submissions')),

    path('src/<int:submission>', submission.SubmissionSource.as_view(), name='submission_source'),
    path('src/<int:submission>/raw', submission.SubmissionSourceRaw.as_view(), name='submission_source_raw'),

    path('submission/<int:submission>', include([
        path('', submission.SubmissionStatus.as_view(), name='submission_status'),
        path('/abort', submission.abort_submission, name='submission_abort'),
    ])),

    path('users/', include([
        path('', user.users, name='user_list'),
        path('<int:page>', lambda request, page:
             HttpResponsePermanentRedirect('%s?page=%s' % (reverse('user_list'), page))),
        path('find', user.user_ranking_redirect, name='user_ranking_redirect'),
    ])),

    path('user', user.UserAboutPage.as_view(), name='user_page'),
    path('edit/profile/', user.edit_profile, name='user_edit_profile'),
    path('data/prepare/', user.UserPrepareData.as_view(), name='user_prepare_data'),
    path('data/download/', user.UserDownloadData.as_view(), name='user_download_data'),
    path('user/<str:user>', include([
        path('', user.UserAboutPage.as_view(), name='user_page'),
        path('/solved', include([
            path('', user.UserProblemsPage.as_view(), name='user_problems'),
            path('/ajax', user.UserPerformancePointsAjax.as_view(), name='user_pp_ajax'),
        ])),
        path('/submissions/', paged_list_view(submission.AllUserSubmissions, 'all_user_submissions_old')),
        path('/submissions/', lambda _, user:

judge/models/ticket.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils.translation import gettext_lazy as _

from judge.models.profile import Profile


class Ticket(models.Model):
    title = models.CharField(max_length=100, verbose_name=_('ticket title'))
    user = models.ForeignKey(Profile, verbose_name=_('ticket creator'), related_name='tickets',
                             on_delete=models.CASCADE)
    time = models.DateTimeField(verbose_name=_('creation time'), auto_now_add=True)
    assignees = models.ManyToManyField(Profile, verbose_name=_('assignees'), related_name='assigned_tickets',
                                       blank=True)
    notes = models.TextField(verbose_name=_('quick notes'), blank=True,
                             help_text=_('Staff notes for this issue to aid in processing.'))
    content_type = models.ForeignKey(ContentType, verbose_name=_('linked item type'),
                                     on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField(verbose_name=_('linked item ID'))
    linked_item = GenericForeignKey()
    is_open = models.BooleanField(verbose_name=_('is ticket open?'), default=True)

    class Meta:
        verbose_name = _('ticket')
        verbose_name_plural = _('tickets')


class TicketMessage(models.Model):
    ticket = models.ForeignKey(Ticket, verbose_name=_('ticket'), related_name='messages',
                               related_query_name='message', on_delete=models.CASCADE)
    user = models.ForeignKey(Profile, verbose_name=_('user'), related_name='ticket_messages',
                             on_delete=models.CASCADE)
    body = models.TextField(verbose_name=_('message body'))
    time = models.DateTimeField(verbose_name=_('message time'), auto_now_add=True)

    class Meta:
        verbose_name = _('ticket message')
        verbose_name_plural = _('ticket messages')

judge/views/preview.py
from django.http import HttpResponseBadRequest
from django.views.generic.base import ContextMixin, TemplateResponseMixin, View


class MarkdownPreviewView(TemplateResponseMixin, ContextMixin, View):
    def post(self, request, *args, **kwargs):
        try:
            self.preview_data = data = request.POST['content']
        except KeyError:
            return HttpResponseBadRequest('No preview data specified.')

        return self.render_to_response(self.get_context_data(
            preview_data=data,
        ))


class ProblemMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'problem/preview.html'


class BlogMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'blog/preview.html'


class ContestMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'contest/preview.html'


class CommentMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'comments/preview.html'


class FlatPageMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'flatpage-preview.html'


class ProfileMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'user/preview.html'


class OrganizationMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'organization/preview.html'


class SolutionMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'solution-preview.html'


class LicenseMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'license-preview.html'


class TicketMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'ticket/preview.html'


class DefaultMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'default-preview.html'

templates/ticket/edit-notes.html
<form id="edit-notes" action="{{ url('ticket_notes', ticket.id) }}" method="post">
    {% csrf_token %}
    {{ form.notes }}
    <button type="submit" class="submit">{{ _('Update') }}</button>
</form>

templates/ticket/message.html
<section id="message-{{ message.id }}" class="ticket-message">
    <div class="info">
        <a href="{{ url('user_page', message.user.user.username) }}" class="user">
            <img src="{{ gravatar(message.user, 80) }}" class="user-gravatar">
        </a>
    </div>
    <div class="detail">
        <div class="header">
            {{ link_user(message.user) }}&nbsp;
            <span class="time">
                {% with abs=_('messaged on {time}'), rel=_('messaged {time}') %}
                    {{ relative_time(message.time, abs=abs, rel=rel) }}
                {% endwith %}
            </span>
            <span class="operation">
                {% if perms.judge.change_ticket and perms.judge.change_ticketmessage %}
                    <a href="{{ url('admin:judge_ticket_change', ticket.id) }}"
                       title="{{ _('Admin') }}"><i class="fa fa-cog fa-fw"></i></a>
                {% endif %}
            </span>
        </div>
        <div class="content content-description">
            {{ message.body|markdown('ticket', MATH_ENGINE)|reference|str|safe }}
        </div>
    </div>
</section>

templates/ticket/new.html
{% extends "base.html" %}

{% block media %}{{ form.media.css }}{% endblock %}

{% block js_media %}{{ form.media.js }}{% endblock %}

{% block body %}
    <form id="ticket-form" action="" method="POST" class="form-area">
        {% block guideline_message %}{% endblock %}
        {% csrf_token %}
        <div class="title-block{% if form.title.errors %} error{% endif %}">{{ form.title }}</div>
        {% if form.errors %}
            <div class="form-errors">
                {{ form.non_field_errors() }}
                {{ form.title.errors }}
                {{ form.body.errors }}
            </div>
        {% endif %}
        <div class="body-block">{{ form.body }}</div>
        <button type="submit" class="submit">{{ _('Create') }}</button>
    </form>
{% endblock %}

templates/ticket/new_problem.html
{% extends "ticket/new.html" %}

{% block guideline_message %}
    {% if not request.in_contest %}
        <div class="alert alert-warning alert-dismissable">
            <a class="close">x</a>
            <b>{{ _('Thanks for opening a ticket!') }}</b>
            <br><br>
            {{ _('Please keep in mind that this form is for reporting issues with a problem statement, and not for asking for help. If you require assistance on solving a problem, ask in the comments instead.') }}
        </div>
    {% endif %}
{% endblock %}

templates/ticket/preview.html
{{ preview_data|markdown('ticket', MATH_ENGINE)|reference|str|safe }}
{% if REQUIRE_JAX %}
    <div data-config="{{ static('mathjax_config.js') }}" class="require-mathjax-support"></div>
{% endif %}

templates/ticket/row.html
<tr id="ticket-{{ ticket.id }}">
    <td><i class="fa {% if ticket.is_open %}fa-exclamation-circle{% else %}fa-check-circle-o{% endif %}"></i></td>
    <td>{{ ticket.id }}</td>
    <td><a href="{{ url('ticket', ticket.id) }}">{{ ticket.title }}</a></td>
    <td>{{ link_user(ticket.user) }}</td>
    <td>{{ link_users(ticket.assignees.all()) }}</td>
</tr>

templates/ticket/ticket.html
{% extends "base.html" %}
{% block media %}{{ form.media.css }}{% endblock %}

{% block js_media %}
    {{ form.media.js }}
    <script src="{{ static('libs/featherlight/featherlight.min.js') }}" type="text/javascript"></script>
    <script type="text/javascript" src="{{ static('event.js') }}"></script>
    <script type="text/javascript">
        $(function () {
            var $h2 = $('#content').find('> h2:first-child');
            var $status = $h2.find('.ticket-title i'), $title = $h2.find('.title');

            function update_ticket_state(open) {
                if (open)
                    $status.removeClass('fa-check-circle-o').addClass('fa-exclamation-circle');
                else
                    $status.removeClass('fa-exclamation-circle').addClass('fa-check-circle-o');
                $('.close-ticket').toggle(open);
                $('.open-ticket').toggle(!open);
            }

            $('.close-ticket, .open-ticket').click(function () {
                var open = $(this).attr('data-open') == '1';
                $.ajax({
                    url: $(this).attr('data-ajax'), type: 'POST',
                    success: function () {
                        update_ticket_state(open);
                    },
                    error: function (data) {
                        alert('{{ _('Could not change ticket: {error}') }}'.replace('{error}', data.responseText));
                    }
                });
            });

            $('.edit-notes').featherlight({
                afterOpen: function () {
                    var $form = $('#edit-notes');
                    $form.find('.submit').click(function () {
                        $.post($form.attr('action'), $form.serialize()).done(function (data) {
                            $('#ticket-notes').find('.info-empty').toggle(!data).end().find('.info-real').html(data);
                            $.featherlight.current().close();
                        });
                        return false;
                    });
                }
            });

            var page_ref_key = 'ticket:open:{{ ticket.id }}', page_close_key = page_ref_key + ':close';
            var page_ref;

            function increase_page_ref() {
                if (page_ref_key in localStorage)
                    localStorage[page_ref_key] = page_ref = +localStorage[page_ref_key] + 1;
                else
                    localStorage[page_ref_key] = page_ref = 1;
            }

            function decrease_page_ref() {
                if (page_ref_key in localStorage) {
                    localStorage[page_close_key] = page_ref;
                    delete localStorage[page_close_key];
                    localStorage[page_ref_key] = +localStorage[page_ref_key] - 1;
                }
                page_ref = null;
            }

            function is_highest_ref() {
                console.log(localStorage[page_ref_key], page_ref);
                if (page_ref_key in localStorage)
                    return +localStorage[page_ref_key] == page_ref;
                return true;
            }

            $(window).on('storage', function (e) {
                e = e.originalEvent;
                if (e.key == page_close_key && e.newValue !== null)
                    if (page_ref != null && page_ref > +e.newValue)
                        --page_ref;
            });

            register_notify('ticket', {
                change: function (enabled) {
                    if (enabled)
                        increase_page_ref();
                }
            });

            $(window).on('beforeunload', function () {
                decrease_page_ref();
            });

            function ticket_status(ticket) {
                update_ticket_state(ticket.open);
                if (is_highest_ref())
                    notify('ticket', (ticket.open ? '{{ _('Reopened: ') }}' :
                        '{{ _('Closed: ') }}') + $title.text());
            }

            function ticket_message(ticket) {
                console.log('Fetching data for: ' + ticket.message);
                $.ajax({
                    url: '{{ url('ticket_message_ajax', ticket.id) }}',
                    data: {message: ticket.message},
                    success: function (data) {
                        console.log('Got data for: ' + ticket.message);
                        console.log(data);
                        $('#messages').append($(data.message));
                    },
                    error: function (data) {
                        if (data.status === 403)
                            console.log('No right to see: ' + ticket.message);
                        else {
                            console.log('Could not load ticket message:');
                            console.log(data.responseText);
                        }
                    }
                });
            }

            window.load_dynamic_update = function (last_msg) {
                return new EventReceiver(
                    "{{ EVENT_DAEMON_LOCATION }}", "{{ EVENT_DAEMON_POLL_LOCATION }}",
                    ['ticket-{{ ticket.id }}'], last_msg, function (message) {
                        console.log(message);
                        switch (message.type) {
                            case 'ticket-status':
                                ticket_status(message);
                                break;
                            case 'ticket-message':
                                ticket_message(message);
                                break;
                        }
                    }
                );
            }
        });
    </script>

    {% if last_msg %}
        <script type="text/javascript">
            $(function () {
                load_dynamic_update({{ last_msg }});
            });
        </script>
    {% endif %}
{% endblock %}

{% block content_title %}
    <div class="ticket-title">
        <i class="fa {% if ticket.is_open %}fa-exclamation-circle{% else %}fa-check-circle-o{% endif %}"></i>
        <div class="title">{{ ticket.title }}</div>
        <small>#{{ ticket.id }}</small>
    </div>
{% endblock %}

{% block body %}
    <div class="ticket-container">
        <div class="ticket-messages">
            <main id="messages">
                {% for message in ticket_messages %}
                    {% include "ticket/message.html" %}
                {% endfor %}
            </main>
            <hr>
            <section class="ticket-message new-message">
                <div class="info">
                    <a href="{{ url('user_page', request.user.username) }}" class="user">
                        <img src="{{ gravatar(request.user, 80) }}" class="user-gravatar">
                    </a>
                </div>
                <div class="detail">
                    <form action="" method="post">
                        {% csrf_token %}
                        {% if form.non_field_errors() or form.body.errors %}
                            <div class="form-errors">
                                {{ form.non_field_errors() }}
                                {{ form.body.errors }}
                            </div>
                        {% endif %}
                        <div class="body-block">{{ form.body }}</div>
                        <button type="submit" class="submit">{{ _('Post!') }}</button>
                    </form>
                </div>
            </section>
        </div>
        <aside class="ticket-sidebar">
            <div class="ticket-info">
                <div class="info-box">
                    <div class="info-title">{{ _('Associated object') }}</div>
                    <div class="info-data">
                        <a href="{{ ticket.linked_item.get_absolute_url() }}">{{ ticket.linked_item }}</a>
                    </div>
                </div>
                <div class="info-box">
                    <div class="info-title">
                        {% trans trimmed count=assignees|length %}
                            Assignee
                        {% pluralize %}
                            Assignees
                        {% endtrans %}
                    </div>
                    <div class="info-data">
                        {% if assignees %}
                            {{ link_users(assignees) }}
                        {% else %}
                            <div class="info-empty">{{ _('No one is assigned.') }}</div>
                        {% endif %}
                    </div>
                </div>

                <button data-ajax="{{ url('ticket_close', ticket.id) }}" data-open="0" class="close-ticket"
                        {% if not ticket.is_open %}style="display: none"{% endif %}>{{ _('Close ticket') }}</button>
                <button data-ajax="{{ url('ticket_open', ticket.id) }}" data-open="1" class="open-ticket"
                        {% if ticket.is_open %}style="display: none"{% endif %}>{{ _('Reopen ticket') }}</button>

                {% if perms.judge.change_ticket or request.profile in assignees %}
                    <div class="info-box">
                        <div class="info-title">{{ _('Assignee notes') }}
                            <a href="#" data-featherlight="{{ url('ticket_notes', ticket.id) }}" class="edit-notes">
                                <i class="fa fa-pencil"></i>
                            </a>
                        </div>
                        <div id="ticket-notes" class="info-data">
                            <div{% if ticket.notes %} style="display: none"{% endif %} class="info-empty">
                                {{ _('Nothing here.') }}
                            </div>
                            <div class="info-real">{{ ticket.notes|linebreaks }}</div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </aside>
    </div>
{% endblock %}

{% block bodyend %}
    {% if REQUIRE_JAX %}
        {% include "mathjax-load.html" %}
    {% endif %}
{% endblock %}